-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Oct 27, 2020 at 10:30 AM
-- Server version: 5.7.32
-- PHP Version: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `arrayg40_healthyways`
--

-- --------------------------------------------------------

--
-- Table structure for table `panel`
--

CREATE TABLE `panel` (
  `id` int(255) NOT NULL,
  `phenotype` varchar(255) NOT NULL,
  `traits` varchar(255) NOT NULL,
  `gene_id` varchar(255) NOT NULL,
  `gene` varchar(255) NOT NULL,
  `genotype` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `all_publication` varchar(255) NOT NULL,
  `snp` varchar(255) NOT NULL,
  `panel_info_id` int(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `panel`
--

INSERT INTO `panel` (`id`, `phenotype`, `traits`, `gene_id`, `gene`, `genotype`, `description`, `all_publication`, `snp`, `panel_info_id`) VALUES
(1, 'Regulation of eating', 'Emotional eating dependence', '4160', 'MC4R', 'TC', 'The protein encoded by this gene is a membrane-bound receptor and member of the melanocortin receptor family. The encoded protein interacts with adrenocorticotropic and MSH hormones and is mediated by G proteins. This is an intronless gene. Defects in thi', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4160', 'rs17782313', 1),
(2, 'Regulation of eating', 'Snacking pattern', '3952', 'near LEP', 'GG', 'This gene encodes a protein that is secreted by white adipocytes into the circulation and plays a major role in the regulation of energy homeostasis. Circulating leptin binds to the leptin receptor in the brain, which activates downstream signaling pathwa', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3952', 'rs7799039', 1),
(3, 'Regulation of eating', 'Snacking pattern', '4160', 'MC4R', 'TC', 'The protein encoded by this gene is a membrane-bound receptor and member of the melanocortin receptor family. The encoded protein interacts with adrenocorticotropic and MSH hormones and is mediated by G proteins. This is an intronless gene. Defects in thi', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4160', 'rs17782313', 1),
(4, 'Regulation of eating', 'Satiety response', '79068', 'FTO', 'TT', 'The FTO gene is one of the genes that has been associated with obesity risk. It is believed to influence satiety and hunger and regulate energy homeostasis. Studies suggest that the FTO gene may play an important role in regulating food intake; variations', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs9939609', 1),
(5, 'Taste Perception', 'Sweet taste perception', '83756', 'TAS1R3', 'CC, CC', 'There are differences in the sensitivity, perception, and preference for tastes. Taste sensitivity can be attributed to the threshold of activated taste cells. The sweet taste perception is primarily mediated by the TAS1R2 (taste receptor type 1 member 2)', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=83756', 'rs307355', 1),
(6, 'Taste Perception', 'Sweet taste perception', '80834', 'TAS1R2', 'CC, GT', 'There are differences in the sensitivity, perception, and preference for tastes. Taste sensitivity can be attributed to the threshold of activated taste cells. The sweet taste perception is primarily mediated by the TAS1R2 (taste receptor type 1 member 2)', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=80834', 'rs12033832', 1),
(7, 'Taste Perception', 'Bitter taste perception', '5726', 'TAS2R38', 'TT, CC', 'The TAS2R38 gene encodes a G protein-coupled receptor, which acts as a taste receptor, and is mediated by certain chemicals like PROP and phenylthiocarbamide; these chemicals bind to the receptor and signal taste perception. Vegetables like broccoli, cabb', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5726', 'rs10246939', 1),
(8, 'Taste Perception', 'Fatty food preference', '9628', 'RGS6', 'GA, CT, GA, TC', 'The RGS6 gene is a member of the G7 superfamily; it plays a role in the regulation of G-protein signaling and is believed to have an interplay with opioid receptors (G-protein coupled receptors). While under stress, there is an increase in the cortisol le', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9628', 'rs1402064', 1),
(10, 'Macronutrient Requirements', 'Response to Carbohydrates', '1636', 'ACE', 'GG', 'The ACE gene provides instructions for making the angiotensin-converting enzyme. The renin-angiotensin system (RAS) is involved in most of the pathological processes that lead to pathogenesis of diabetes. Angiotensin II (Ang II) is the major peptide of RA', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1636', 'rs4343', 1),
(11, 'Macronutrient Requirements', 'Response to Carbohydrates', '154', 'ADRB2', 'CC', 'This gene encodes beta-2-adrenergic receptor which is a member of the G protein-coupled receptor superfamily. Receptors involved in catecholamine function have a role in thermogenesis and energy balance, thus affecting obesity and glucose metabolism. Adre', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=154', 'rs1042713', 1),
(12, 'Macronutrient Requirements', 'Response to Carbohydrates', '326625', 'MMAB', 'CC', 'The MMAB gene encodes an enzyme that aids in the production of adenosylcobalamin, which is important for the breakdown of cholesterol. The MMAB gene may play a role in modulating concentrations of HDL-C which can affect the risk of developing dyslipidemia', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=326625', 'rs2241201', 1),
(13, 'Macronutrient Requirements', 'Response to Carbohydrates', '6720', 'SREBP1C', 'TT, CC', 'Sterol regulatory element binding protein-1c (SREBP1C) is a transcription factor involved in the regulation of lipid, glucose metabolism and in sterol homoeostasis in cells. SREBP1C expression is regulated by nutritional stimuli like polyunsaturated fatty', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6720', 'rs2297508', 1),
(14, 'Macronutrient Requirements', 'Response to Carbohydrates', '5465', 'PPARA', 'GG', 'The shift between glucose storage and synthesis during fasting and feeding is essential for maintaining blood glucose levels. PPARA contributes to the adaptation of hepatic carbohydrate metabolism during the fasting-to-fed and fed-to-fasting transition. H', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5465', 'rs1800206', 1),
(15, 'Macronutrient Requirements', 'Response to Carbohydrates', '5468', 'PPARG', 'CC', 'PPAR (peroxisome proliferator-activated receptor) is involved in regulating the carbohydrate and lipid homeostasis, adipogenesis, fatty acid storage, and maintaining energy balance. The PPARG gene encodes a protein (PPAR-gamma) which plays a role in the r', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5468', 'rs1800571', 1),
(16, 'Macronutrient Requirements', 'Response to Carbohydrates', '6934', 'TCF7L2', 'AA, CC, GG', 'The TCF7L2 gene encodes a protein that influences the secretion of a hormone (glucagon-like peptide-1) which has insulinotropic effects (stimulates insulin secretion) and plays a role in regulating blood glucose homeostasis. Carbohydrate digestion causes ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6934', 'rs7903146', 1),
(17, 'Macronutrient Requirements', 'Response to Carbohydrates', '79068', 'FTO', 'CC', 'The expression of the FTO gene in the hypothalamus is indicative of its potential role in regulating energy homeostasis by modifying the appetite. Carbohydrates influence various aspects such as body weight, appetite, and endocrinology. Carbohydrates inta', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs1421085', 1),
(18, 'Macronutrient Requirements', 'Response to saturated fats', '5122', 'PCSK1', 'GG', 'The PCSK1 gene encodes for a protein that has been associated with the cleavage of proteins that play a role in the hypothalamic regulation of appetite. Variations in the PCSK1 gene have been associated with the modulation of fasting fat oxidation.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5122', 'rs6230', 1),
(19, 'Macronutrient Requirements', 'Response to saturated fats', '4049', 'LTA', 'TA', 'Variations that influence the function of the gene have been identified in several genes, including the lymphotoxin-Î± (LTA) gene, which affects the cytokine production. The variations may interact with dietary fatty acids to regulate the production and s', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4049', 'rs915654', 1),
(20, 'Macronutrient Requirements', 'Response to saturated fats', '7067', 'THRA', 'AA', 'The THRA gene encodes for a protein which is a nuclear hormone receptor for triiodothyronine (T3 thyroid hormone). It is shown to mediate certain activities of the thyroid hormone. Thyroid hormones, Triiodothyronine (T3) and tetraiodothyronine (T4) hormon', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7067', 'rs137853162', 1),
(21, 'Macronutrient Requirements', 'Response to saturated fats', '4035', 'LRP1', 'CT', 'The LRP1 gene encodes a protein, which is involved in the formation of a mature receptor. This receptor is involved in many cellular processes including intracellular signaling, lipid homeostasis, and clearance of apoptotic cells (biochemical events leadi', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4035', 'rs483353013', 1),
(22, 'Macronutrient Requirements', 'Response to saturated fats', '197', 'AHSG', 'CC', 'The AHSG gene is involved in the regulation of body fat and insulin sensitivity. Variations in the AHSG gene has been shown to be associated with reduced plasma levels as well as lower body fat.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=197', 'rs4917', 1),
(23, 'Macronutrient Requirements', 'Response to saturated fats', '4023', 'LPL', 'CC', 'Lipoprotein lipase (LPL), associated with the luminal endothelial surface of arteries and capillaries of peripheral tissues,it is a key enzyme in the metabolism of lipoproteins. It hydrolyzes plasma lipoprotein triglycerides into free fatty acids and glyc', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4023', 'rs13702', 1),
(24, 'Macronutrient Requirements', 'Response to saturated fats', '948', 'CD36', 'AG', 'The CD36 gene encodes for a membrane-bound protein; CD36 is expressed in several cell types, including fat cells and muscle cells. The primary function of this protein is in the uptake of fatty acids into cells for energy generation. CD36 and FA signaling', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=948', 'rs3211938', 1),
(25, 'Macronutrient Requirements', 'Response to saturated fats', '3569', 'IL6', 'AA, CC, GG', 'The IL6 gene encodes for a protein that has a wide variety of biological functions. Following muscle contraction, it functions to increase the breakdown of fats and to improve insulin resistance.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3569', 'rs1800795', 1),
(26, 'Macronutrient Requirements', 'Response to saturated fats', '336', 'APOA2', 'TT', 'The APOA2 gene encodes for a protein, apolipoprotein (apo-) A-II, which is the second most abundant protein of the high-density lipoprotein particles. Saturated fat can stimulate the production for APOA2 production in the postprandial phase (after eating ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=336', 'rs202223831', 1),
(27, 'Macronutrient Requirements', 'Response to saturated fats', '5465', 'PPARA', 'TT', 'The PPARA gene plays a key role in lipid homeostasis. The activation of PPARA contributes to the clearance of triglyceride-rich lipoproteins, improves HDL cholesterol concentrations, and reduces the oxidation of LDL cholesterol, thus influencing the activ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5465', 'rs1801282', 1),
(28, 'Macronutrient Requirements', 'Response to saturated fats', '5468', 'PPARG', 'CC', 'This gene encodes a member of the peroxisome proliferator-activated receptor (PPAR) subfamily of nuclear receptors. The protein encoded by this gene is PPAR-gamma and is a regulator of adipocyte differentiation. PPARG regulates fatty acid storage and gluc', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5468', 'rs1800571', 1),
(29, 'Macronutrient Requirements', 'Response to saturated fats', '6934', 'TCF7L2', 'GG', 'This gene encodes a transcription factor that influences the secretion of GLP 1 (glucagon like peptide 1) which is insulinotropic (stimulates insulin secretion) and has a role in blood glucose homeostasis. TCF7L2 is expressed in subcutaneous and visceral ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6934', 'rs12255372', 1),
(30, 'Macronutrient Requirements', 'Response to saturated fats', '79068', 'FTO', 'TT', 'The FTO gene has strong associations with conditions such as obesity and type II diabetes. It is known to contribute to the regulation of body size and body fat accumulation, specifically, thermogenesis (heat production), and adipocyte (fat cell) differen', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs9939609', 1),
(31, 'Macronutrient Requirements', 'Response to Monosaturated fats', '335', 'APOA1', 'AA', 'The APOA1 gene encodes for a protein, apolipoprotein A-I (ApoA-1), which is the major protein component of high-density lipoprotein (HDL) in the plasma. High levels of HDL can reduce the risk of developing cardiovascular conditions. HDL transports cholest', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=335', 'rs670', 1),
(32, 'Macronutrient Requirements', 'Response to Monosaturated fats', '9370', 'ADIPOQ', 'GG, GG', 'The ADIPOQ gene encodes for a protein, adiponectin, which is a plasma protein secreted by the visceral adipose tissue. Adiponectin increases insulin sensitivity and tissue fat oxidation, resulting in reduced circulating fatty acid levels. Therefore, varia', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs144526209 ', 1),
(33, 'Macronutrient Requirements', 'Response to Monosaturated fats', '338', 'APOB', 'AA', 'The APOB gene encodes for a protein, apolipoprotein B, which is the main apolipoprotein of chylomicrons and low-density lipoproteins. This protein is involved in transporting fat molecules, including cholesterol in the bloodstream.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=338', 'rs693', 1),
(35, 'Macronutrient Requirements', 'Response to polysaturated fats', '1071', 'CETP', 'GT, CT', 'The CETP gene encodes for a protein that is involved in the transfer of cholesteryl ester from high-density lipoprotein (HDL) to other lipoproteins. Variations in the CETP gene may influence the responses of lipids (fats) and lipoproteins to the alteratio', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1071', 'rs2303790', 1),
(36, 'Macronutrient Requirements', 'Response to polysaturated fats', '183', 'AGT', 'CT', 'The AGT gene encodes for a protein, angiotensinogen, which plays a role in the regulation of blood pressure and fluid balance in the body. Variations in the AGT gene have found to be associated with concentrations of total cholesterol and low-density lipo', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=183', 'rs699', 1),
(37, 'Macronutrient Requirements', 'Response to polysaturated fats', '3992', 'FADS1', 'GG, TT', 'This gene encodes the enzyme Fatty acid desaturase 1(Î”5 desaturase) which catalyses the conversion of omega-3 & omega-6 parent fatty acids namely alpha-linolenic acid (ALA) & linoleic acid (LA) to their longer chain derivatives (eicosapentaenoic acid or ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3992', 'rs174544', 1),
(38, 'Macronutrient Requirements', 'Response to polysaturated fats', '345', 'APOC3', 'CC', 'The APOC3 gene encodes for a protein, apolipoprotein C-3 (APOC3), which is a component of very-low-density lipoprotein (VLDL). This gene plays a role in inhibiting the activities of proteins that are required for the hydrolysis of triglycerides and theref', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=345', 'rs2070666', 1),
(39, 'Macronutrient Requirements', 'Response to polysaturated fats', '116519', 'APOA5', 'AA, TT', 'The APOA5 gene encodes for a protein, apolipoprotein A-5 (APOA5), which is a major component of VLDL (very low-density lipoprotein), chylomicrons, and HDL (high-density lipoprotein). APOA5 functions as an activator of a key enzyme in triglyceride cataboli', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=116519', 'rs662799', 1),
(40, 'Macronutrient Requirements', 'Response to polysaturated fats', '9370', 'ADIPOQ', 'TT', 'The ADIPOQ gene encodes for a protein, adiponectin, which is a plasma protein secreted by the visceral adipose tissue. Adiponectin increases insulin sensitivity and tissue fat oxidation, resulting in reduced circulating fatty acid levels. Therefore, varia', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs144526209 ', 1),
(41, 'Macronutrient Requirements', 'Response to protein', '4544', 'MTNR1B', 'CG', 'This gene encodes one of two high affinity forms of a receptor for melatonin, the primary hormone secreted by the pineal gland. Given that melatonin is a hormone involved in energy balance and body weight status, this gene is implicated in body weight reg', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4544', 'rs10830963', 1),
(42, 'Macronutrient Requirements', 'Response to protein', '7021', 'TFAP2B', 'AA', 'The TFAP2B gene encodes a protein (transcription factor AP-2Î²), which in conjunction with other proteins from the AP-2 family binds to specific regions of DNA and helps to control the activity of genes involved in the stimulation of cell proliferation an', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7021', 'rs2817399', 1),
(43, 'Macronutrient Requirements', 'Response to protein', '79068', 'FTO', 'TT', 'This gene encodes for a nuclear protein of the AlkB related non-haem iron and 2-oxoglutarate-dependent oxygenase superfamily. RNA demethylase that mediates oxidative demethylation of different RNA species, such as mRNAs, tRNAs and snRNAs, and acts as a re', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs9939609', 1),
(44, 'Macronutrient Requirements', 'Response to fibre', '79068', 'FTO', 'AA', 'The FTO gene has strong associations with conditions such as obesity and type II diabetes. Studies have shown that people with certain variations in the FTO gene are found to have beneficial results with increased fiber intake; variations may also be asso', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs9939609', 1),
(46, 'Weight Management and Maintenance', 'Ability to maintain the weight loss', '9370', 'ADIPOQ', 'GG', 'The ADIPOQ gene encodes for a protein, adiponectin, which is produced in the adipose tissue (fat tissue). Variations in the ADIPOQ gene can influence the production of adiponectin, thereby affecting energy intake and body weight.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs144526209 ', 1),
(47, 'Weight Management and Maintenance', 'Ability to maintain the weight loss', '5468', 'PPARG', 'CC', 'PPAR (peroxisome proliferator-activated receptor) is involved in regulating the carbohydrate and lipid homeostasis, adipogenesis, fatty acid storage, and maintaining energy balance. The PPARG gene encodes a protein (PPAR-gamma) which plays a role in the r', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5468', 'rs1800571', 1),
(48, 'Weight Management and Maintenance', 'Ability to maintain the weight loss', '79068', 'FTO', 'GG', 'The FTO gene has strong associations with conditions such as obesity and type II diabetes. Variations in the FTO gene may influence weight regain', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs9939609', 1),
(49, 'Micronutrient Requirements', 'Vitamin A Metabolism', '53630', 'near BCMO1', 'GG, TG', 'The protein encoded by this gene is a key enzyme in beta-carotene metabolism to vitamin A. It catalyzes the oxidative cleavage of beta-carotene into two retinal molecules. Vitamin A metabolism is important for vital processes such as vision, embryonic dev', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=53630', 'rs11645428', 1),
(50, 'Micronutrient Requirements', 'Vitamin A Metabolism', '53630', 'BCMO1', 'AA, AA, CC', 'The protein encoded by this gene is a key enzyme in beta-carotene metabolism to vitamin A. It catalyzes the oxidative cleavage of beta-carotene into two retinal molecules. Vitamin A metabolism is important for vital processes such as vision, embryonic dev', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=53630', 'rs11645428', 1),
(52, 'Micronutrient Requirements', 'Vitamin D Metabolism', '2638', 'GC', 'AC, GT', 'The GC gene encodes the vitamin D binding protein (DBP) that belongs to the albumin gene family. The encoded protein has multiple functions and is found in the plasma, ascitic fluid, cerebrospinal fluid, and on the surface of many cell types. The protein ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2638', 'rs2282679', 1),
(53, 'Micronutrient Requirements', 'Vitamin D Metabolism', '7421', 'VDR', 'TT, CA', 'Vitamin D can either be acquired through dietary intake or made in the body with help from sunlight exposure. The VDR gene encodes the vitamin D receptor (VDR) protein which plays a role in the bodyâ€™s response to vitamin D. It binds to calcitriol, the a', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7421', 'rs1544410', 1),
(54, 'Micronutrient Requirements', 'Vitamin E Metabolism', '337', 'APOA4', 'TT', 'APOA4 encodes an apoprotein secreted by the intestine and associated with chylomicrons. APOA4 gene has a role in chylomicrons and VLDL secretion and catabolism. Required for efficient activation of lipoprotein lipase by ApoC-II.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=337', 'rs5104', 1),
(55, 'Micronutrient Requirements', 'Vitamin E Metabolism', '948', 'CD36', 'AG, GG, TT', 'Vitamin E is a fat-soluble vitamin and an antioxidant. The protein encoded by the CD36 gene is involved in the uptake of long-chain fatty acids and therefore may also influence the plasma concentrations of vitamin E.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=948', 'rs1761667', 1),
(56, 'Micronutrient Requirements', 'Vitamin B6 Metabolism', '84224', 'Near NBPF3', 'CT', 'This variant is located near the NBPF3 gene. Variants of the NBPF3 gene were found to be associated with the plasma concentration of pyridoxal phosphate (PLP). PLP is an active form of vitamin B6, which is involved in several enzymatic reactions.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=84224', 'rs4654748,', 1),
(57, 'Micronutrient Requirements', 'Vitamin B6 Metabolism', '84224', 'NBPF3', 'CT', 'The variant in this gene has been associated with decreased levels of Vitamin B6 (pyridoxine). Pyridoxine, one of the forms of Vitamin B6, strengthens the protein collagenâ€™s regenerative ability which is much needed for rendering us flexibility and skin', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=84224', 'rs4654748,', 1),
(58, 'Micronutrient Requirements', 'Vitamin B9 Metabolism', '4524', 'MTHFR', 'AA', 'The MTHFR gene encodes for an enzyme (methylenetetrahydrofolate reductase) which has a role in the processing of amino acids. This enzyme is involved in the chemical reaction involving the vitamin B9 (folate). It plays a role in the conversion of a form o', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4524', 'rs868014', 1),
(59, 'Micronutrient Requirements', 'Vitamin B12 Metabolism', '4552', 'MTRR', 'GG', 'Methionine synthase reductase also known as MSR is an enzyme that in humans is encoded by the MTRR gene. The Methionine Synthase Reductase (MTRR) gene primarily acts in the reductive regeneration of cobalamin (vitamin B12). Cob(I)alamin is a cofactor that', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4552', 'rs16187', 1),
(60, 'Micronutrient Requirements', 'Vitamin B12 Metabolism', '51293', 'CD320', 'CC', 'This gene encodes the transcobalamin receptor that is expressed at the cell surface. It mediates the cellular uptake of transcobalamin bound cobalamin (vitamin B12), and is involved in B-cell proliferation and immunoglobulin secretion. Mutations in this g', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=51293', 'rs2336573', 1),
(61, 'Micronutrient Requirements', 'Vitamin B12 Metabolism', '4548', 'MTR', 'AA', 'The MTR gene provides instructions for making an enzyme called methionine synthase. This enzyme plays a role in processing amino acids, the building blocks of proteins. To function properly, methionine synthase requires methylcobalamin (a form of vitamin ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4548', 'rs3737965', 1),
(62, 'Micronutrient Requirements', 'Vitamin B12 Metabolism', '8029', 'CUBN', 'AA', 'Vitamin B12 is not synthesized in the body and is obtained from dietary intake. The CUBN gene encodes a protein, cubilin, which is the intestinal receptor for vitamin B12 (also called cobalamin). Therefore, the CUBN gene plays a crucial role in vitamin B1', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=8029', 'rs1801222', 1),
(63, 'Micronutrient Requirements', 'Vitamin B12 Metabolism', '2524', 'FUT2', 'AA, GG', 'The FUT2 gene encodes for an enzyme (galactoside 2-alpha-L-fucosyltransferase 2), which influences the synthesis of H-antigen. The H-antigen plays a role in the attachment of H. pylori bacteria to the gastric mucosa; H. pylori infection can cause decrease', 'https://www.ncbi.nlm.nih.gov/gene/2524#bibliography', 'rs601338Â ', 1),
(64, 'Micronutrient Requirements', 'Iron Metabolism', '164656', 'TMPRSS6', 'CT,AG', 'The TMPRSS6 gene encodes a protein called matriptase-2, which influences the levels of the protein, hepcidin. Hepcidin is important for the regulation of iron balance in the body. Low levels of iron in the blood, can decrease the production of hepcidin wh', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=164656', 'rs855791Â ', 1),
(65, 'Micronutrient Requirements', 'Iron Metabolism', '3077', 'HFE', 'CC, GG', 'The HFE gene encodes for a membrane protein that binds to the transferrin receptor 1 protein. This process prevents the receptor from binding to another protein called transferrin. However, binding of transferrin receptor 1 to transferrin is required for ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3077', 'rs1799945', 1),
(66, 'Micronutrient Requirements', 'Antioxidant Metabolism', '2950', 'GSTP1', 'AG, CC', 'Glutathione S-transferase P1 is an enzyme encoded by the GSTP1 gene. This enzyme plays a key role in the process of detoxification and the antioxidant system.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2950', 'rs1695', 1),
(67, 'Micronutrient Requirements', 'Antioxidant Metabolism', '5444', 'PON1', 'TC', 'This gene encodes a member of the paraoxonase family of enzymes and exhibits lactonase and ester hydrolase activity. The HDL associated esterase/lactonase paraoxonase 1 (PON1) is implicated in contributing to the anti-inflammatory and antioxidant activiti', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5444', 'rs854560', 1),
(68, 'Micronutrient Requirements', 'Antioxidant Metabolism', '6648', 'SOD2', 'TT', 'The SOD2 gene encodes an enzyme, manganese-dependent superoxide dismutase (MnSOD), which binds to the superoxide byproducts and helps in their conversion to hydrogen peroxide and diatomic oxygen. Superoxides are harmful to the body as they can damage DNA ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6648', ' rs4880', 1),
(69, 'Micronutrient Requirements', 'Antioxidant Metabolism', '847', 'CAT', 'TC', 'The CAT gene encodes an enzyme, catalase, which is a key antioxidant enzyme that plays a role in the bodyâ€™s defense against oxidative stress. Catalase is involved in the conversion of hydrogen peroxide to water and oxygen which reduces the toxic effects', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=847', 'rs4880', 1),
(70, 'Micronutrient Requirements', 'Antioxidant Metabolism', '2876', 'GPX1', 'CT, CC', 'The GPX1 gene encodes an enzyme (glutathione peroxidase 1 - GPX1), which is an important antioxidant enzyme in the body. Glutathione peroxidase plays a role in the breakdown of hydrogen peroxide and thereby helps to protect cells against oxidative damage.', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2876', 'rs1050450', 1),
(71, 'Micronutrient Requirements', 'Calcium Metabolism', '1591', 'CYP24A1', 'AA', 'CYP24A1 encodes a cytochrome P450 enzyme that hydroxylates 1,25-(OH)2D, into metabolites targeted for degradation and appears to be one of the central regulator of 1,25-(OH)2-D metabolism. CYP24A1 is highly regulated by its own substrate 1,25(OH)2-D, as w', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1591', 'rs777676129', 1),
(72, 'Micronutrient Requirements', 'Calcium Metabolism', '2625', 'Near GATA3', 'CT', 'GATA3 belongs to a family of zinc finger transcription factors that are involved in vertebrate embryonic development. In addition, GATA3 is also expressed in the developing parathyroids, inner ear, and kidneys. GATA3 is implicated in monogenic disorders o', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2625', 'rs4143094Â ', 1),
(73, 'Micronutrient Requirements', 'Calcium Metabolism', '160851', 'Near DGKH', 'GG', 'This gene encodes a member of the diacylglycerol kinase (DGK) enzyme family. Members of this family are involved in regulating intracellular concentrations of diacylglycerol and phosphatidic acid. ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=160851', 'rs4142110', 1),
(74, 'Micronutrient Requirements', 'Calcium Metabolism', '2646', 'GCKR', 'CC', 'Glucokinase (GCK) controls the rate of glucose metabolism in pancreatic cells, and its activity is rate-limiting for insulin secretion. ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2646', 'rs11977526', 1),
(75, 'Micronutrient Requirements', 'Calcium Metabolism', '846', 'CASR', 'AA, GG', 'The CASR gene encodes for a protein (calcium-sensing receptor - CaSR), which is abundant in the cells within the parathyroid glands and the renal tubules of kidneys. The parathyroid hormone produced by the parathyroid glands helps in increasing blood calc', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=846', 'rs9740', 1),
(76, 'Micronutrient Requirements', 'Phosphate Metabolism', '846', 'CASR', 'AA', 'The CASR gene encodes for a protein (calcium-sensing receptor - CaSR), which is abundant in the cells within the parathyroid glands and the renal tubules of kidneys. Phosphate levels depend on parathyroid hormone (PTH) level and CaSR influences PTH levels', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=846', 'rs9740', 1),
(77, 'Micronutrient Requirements', 'Magnesium Metabolism', '846', 'CASR', 'AA', 'The CASR gene encodes for a protein (calcium-sensing receptor - CaSR), which is abundant in the cells within the parathyroid glands and the renal tubules of kidneys. The CaSR protein can bind to magnesium, which can inhibit the secretion of parathyroid ho', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=846', 'rs9740', 1),
(78, 'Micronutrient Requirements', 'Vitamin K metabolism', '8529', 'CYP4F2', 'CT', 'The cytochrome P450 proteins are monooxygenases which catalyze many reactions involved in drug metabolism and synthesis of cholesterol, steroids and other lipids. CYP4F2 regulates the bioavailability of vitamin E and vitamin K, a cofactor that is critical', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=8529', 'rs2108622', 1),
(79, 'Micronutrient Requirements', 'Vitamin K metabolism', '79001', 'VKORC1', 'CC', 'The VKORC1 gene provides instructions for making a vitamin K epoxide reductase enzyme. The VKORC1 enzyme is made primarily in the liver. It spans the membrane of a cellular structure called the endoplasmic reticulum, which is involved with protein process', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79001', 'rs1639', 1),
(80, 'Food Intolerances and Sensitivities ', 'Salt Metabolism', '6446', 'near SGK1', 'CT', 'This variant is located near the SGK1 gene. The SGK1 gene encodes a protein that plays a key role in cellular stress response. It is also known to activate certain sodium, chloride, and potassium channels, which suggests its involvement in regulating seve', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6446', 'rs9493857', 1),
(81, 'Food Intolerances and Sensitivities ', 'Caffeine Metabolism', '1544', 'Near CYP1A2', 'CC, CC', 'Encodes a type of human polycyclic aromatic hydrocarbon-inducible cytochrome P450(CYP1) family called the CYP1A2 enzyme. CYP1A2 demethylates caffeine molecules into substances like paraxanthine & methylxanthine(which can be excreted through urine), reduci', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1544', 'rs762551Â ', 1),
(82, 'Food Intolerances and Sensitivities ', 'Caffeine Metabolism', '6446', 'CYP1A2', 'AA', 'The CYP1A2 gene encodes a liver enzyme that is critical for the breakdown of caffeine molecules into substances that can be excreted through urine. This function influences the amount of caffeine its effects in the body. Variations in the CYP1A2 gene can ', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1544', 'rs762551Â ', 1),
(83, 'Food Intolerances and Sensitivities ', 'Gluten Intolerence', '117289', 'TAGAP', 'AA', 'The TAGAP gene encodes for a protein that may play a role in Rho GTPase-activating protein. Variations in the TAGAP gene may lead to an increase in GTPase activity, which can eventually result in the development of celiac disease (CD). Variants of this ge', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=117289', 'rs1464510', 1),
(84, 'Food Intolerances and Sensitivities ', 'Gluten Intolerence', '3122', 'HLA-DRA', 'TT', 'The HLA-DRA gene (major histocompatibility complex, class II, DR alpha) encodes for a protein that plays a crucial role in the regulation of the immune system. Variations may lead to an immune response in response to gluten intake and may influence an ind', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3122', 'rs7194', 1),
(85, 'Food Intolerances and Sensitivities ', 'Gluten Intolerence', '5966', 'REL', 'AA', 'The REL gene encodes a protein, c-Rel, which belongs to the Rel/NF-ÎºB transcription factor family, which helps in the regulation of genes involved in important processes like inflammation and immune response. Studies have suggested an association of c-RE', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5966', 'rs842644', 1),
(86, 'Food Intolerances and Sensitivities ', 'Gluten Intolerence', '5996', 'Intergenic â€“ RGS1', 'AA', 'RGS1 belongs to a family of RGS genes. It attenuates the signaling activity of G-proteins, blocking the homing of Intra Epithelial Lymphocytes (IELs), and it is specifically expressed both in human small intestinal mucosa and in murine IELs, key players i', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5996', 'rs2816316', 1),
(87, 'Food Intolerances and Sensitivities ', 'Gluten Intolerence', '2524', 'FUT2', 'GG', 'The FUT2 gene encodes for a protein that influences the production of H antigen, which is an antigen essential for the synthesis of soluble A and B antigen. These antigens act as anchors and as sources of carbon for intestinal bacteria in the intestinal l', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2524', 'rs601338', 1),
(88, 'Food Intolerances and Sensitivities ', 'Lactose Intolerence', '4175', 'MCM6', 'CC,CC', 'A regulatory element (which is a specific DNA sequence), within the MCM6 gene, plays a key role in regulating the activity or expression of the LCT gene. The LCT gene encodes an enzyme, lactase, which helps in the metabolism of lactose. Reduced activity o', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4175', 'rs13910', 1),
(1267, 'CVD', 'Myocardial Infraction', '79068', 'FTO', 'TT', 'This gene is a nuclear protein of the AlkB related non-haem iron and 2-oxoglutarate-dependent oxygenase superfamily but the exact physiological function of this gene is not known. Other non-heme iron enzymes function to reverse alkylated Diabetic nephropa', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs9939609', 4),
(1268, 'CVD', 'Cardiomyopathy', '4000', 'LMNA', 'CC', 'LMNA produces the major lamin A and C proteins, and the minor A10 and C2 proteins by alternative splicing within exon 10, which are differentially expressed in a developmentally and tissue specific manner.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4000', ' rs4641', 4),
(1265, 'CVD', 'Myocardial Infraction', '54805', 'CNNM2', 'GG', 'This gene encodes a member of the ancient conserved domain containing protein family. Members of this protein family contain a cyclin box motif and have structural similarity to the cyclins. The encoded protein may play an important role in magnesium home', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=54805', 'rs12411886', 4),
(1266, 'CVD', 'Myocardial Infraction', '100048912', 'CDKN2B-AS1', 'GG', 'This gene lies adjacent to the tumor suppressor gene CDKN2A in a region that is frequently mutated and deleted in a wide variety of tumors. This gene encodes a cyclin-dependent kinase inhibitor, which forms a complex with CDK4 or CDK6, and prevents the ac', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=100048912', 'rs10757274', 4),
(1264, 'CVD', 'Myocardial Infraction', '6387', 'CXCL12', 'TC', 'Chemokine (C-X-C motif) ligand 12 (CXCL12), also called stromal cell-derived factor-1 (SDF-1), is one of the members of CXC chemokine family and mostly known for its crucial role in the accumulation of smooth muscle progenitor cells (SPCs). It will trigge', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6387', 'rs1746048', 4),
(1263, 'CVD', 'Myocardial Infraction', '3988', 'LIPA', 'TT', 'The LIPA gene encodes lysosomal acid lipase (LAL), which hydrolyzes cholesteryl esters and triglycerides in the lysosome of cells to generate free cholesterol and free fatty acids. Any alteration of LAL could produce an accumulation of triglycerides and c', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3988', 'Â rs1051338', 4),
(1262, 'CVD', 'Myocardial Infraction', '57608', 'JCAD', 'CC', 'JCAD (Junctional Cadherin-5 Associated Protein) gene, previously known as KIAA1462. JCAD is a cell-cell junction-associated protein expressed in endothelial cells, we speculate that JCAD plays a significant role in angiogenesis. Angiogenesis plays an impo', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=57608', 'rs3739998', 4),
(1260, 'CVD', 'Myocardial Infraction', '6597', 'SMARCA4 ', 'GG', 'SMARCA4 gene encodes an ATP-dependent helicase BRG1 and it belongs to SWI/SNF (switching defective/sucrose nonfermenting) complex. SWI/SNF complexes are heterogeneous, BRG1 (also known as SMARCA4) and BRM (also known as SMARCA2) are the only catalytic sub', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6597', 'rs11879293', 4),
(1261, 'CVD', 'Myocardial Infraction', '563897', 'Near ABO', 'TT', 'ABO blood group system is associated with cognitive impairment, preeclampsia, bleeding, neoplastic diseases, and even longevity. mechanism of relationship between ABO blood group and venous thrombosis is elucidated, and its major determinants are von Will', '', 'rs505922 ', 4),
(1259, 'CVD', 'Coronary Artery Disease', '6934', 'TCF7L2', 'CC', 'This gene encodes a high mobility group (HMG) box-containing transcription factor that plays a key role in the Wnt signaling pathway. The protein has been implicated in blood glucose homeostasis. Genetic variants of this gene are associated with increased', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6934', 'rs7903146', 4),
(1257, 'CVD', 'Coronary Artery Disease', '9734', 'HDAC9', 'GA', 'Histones play a critical role in transcriptional regulation, cell cycle progression, and developmental events. Histone acetylation/deacetylation alters chromosome structure and affects transcription factor access to Diabetic nephropathyA. The protein enco', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9734', 'rs2107595', 4),
(1258, 'CVD', 'Coronary Artery Disease', '9370', 'ADIPOQ', 'TT, GT', 'This gene is expressed in adipose tissue exclusively. It encodes a protein with similarity to collagens X and VIII and complement factor C1q. The encoded protein circulates in the plasma and is involved with metabolic and hormonal processes. Mutations in ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs17300539', 4),
(1256, 'CVD', 'Coronary Artery Disease', '1071', 'CETP', 'GG', 'The protein encoded by this gene is found in plasma, where it is involved in the transfer of cholesteryl ester from high density lipoprotein (HDL) to other lipoproteins. Defects in this gene are a cause of hyperalphalipoproteinemia 1.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1071', 'Rs708272', 4),
(1254, 'CVD', 'Coronary Artery Disease', '375056', 'MIA3', 'CC', 'The MIA3 encodes for a protein that is shown to be involved in the export of collagen VII and ApoB within cells, and the protein may also play a role in the secretion of collagens I, II, III, IV, VII and IX. This may suggest an association with the risk o', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=375056', 'Â rs17465637 ', 4),
(1255, 'CVD', 'Coronary Artery Disease', '5444', 'PON1', 'TC', 'This gene encodes a member of the paraoxonase family of enzymes and exhibits lactonase and ester hydrolase activity. Following synthesis in the kidney and liver, the enzyme is secreted into the circulation, where it binds to high density lipoprotein (HDL)', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5444', 'Â rs662', 4),
(1253, 'CVD', 'Coronary Artery Disease', '490', 'ATP2B1', 'CC', 'The protein encoded by this gene belongs to the family of P-type primary ion transport ATPases characterized by the formation of an aspartyl phosphate intermediate during the reaction cycle. These enzymes remove bivalent calcium ions from eukaryotic cells', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=490', 'Â rs17249754', 4),
(1250, 'CVD', 'Coronary Artery Disease', '7941', 'PLA2G7', 'GG', 'The protein encoded by this gene is a secreted enzyme that catalyzes the degradation of platelet-activating factor to biologically inactive products. Defects in this gene are a cause of platelet-activating factor acetylhydrolase deficiency.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7941', 'Â rs1805017', 4),
(1251, 'CVD', 'Coronary Artery Disease', '7040', 'TGFB1', 'CC', 'This gene encodes a secreted ligand of the TGF-beta (transforming growth factor-beta) superfamily of proteins. Ligands of this family bind various TGF-beta receptors leading to recruitment and activation of SMAD family transcription factors that regulate ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7040', 'rs1800469 ', 4),
(1252, 'CVD', 'Coronary Artery Disease', '929', 'CD14', 'CT', 'The protein encoded by this gene is a surface antigen that is preferentially expressed on monocytes/macrophages. It cooperates with other proteins to mediate the innate immune response to bacterial lipopolysaccharide.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=929', 'rs2569190', 4),
(1249, 'CVD', 'Atrial Fibrillation', '183', 'AGT', 'CT', 'The protein encoded by this gene, pre-angiotensinogen or angiotensinogen precursor, is expressed in the liver and is cleaved by the enzyme renin in response to lowered blood pressure. The protein is involved in maintaining blood pressure and in the pathog', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=183', 'Â rs699', 4),
(1248, 'CVD', 'Atherosclerosis', '9734', 'HDAC9', 'GA', 'Histones play a critical role in transcriptional regulation, cell cycle progression, and developmental events. Histone acetylation/deacetylation alters chromosome structure and affects transcription factor access to Diabetic nephropathy. The protein encod', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9734', 'rs2107595 ', 4),
(1247, 'CVD', 'Atherosclerosis', '958', 'CD40', 'TT', 'CD40 a 50kDa cell surface transmembrane glycoprotein receptor of the tumor necrosis factor receptor (TNFR) superfamily, which is expressed on the surface of immune cells as well as non-immune cells, determines T cell responses to antigen presentation and ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=958', 'rs1535045 ', 4),
(1246, 'CVD', 'Atherosclerosis', '4982', 'TNFRSF11B', 'GC', 'The protein encoded by this gene is a member of the TNF-receptor superfamily. This protein is an osteoblast-secreted decoy receptor that functions as a negative regulator of bone resorption. This protein specifically binds to its ligand, osteoprotegerin l', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4982', 'rs1485286 ', 4),
(1245, 'CVD', 'Stroke', '154', 'ADRB2', 'CC', 'This gene encodes beta-2-adrenergic receptor which is a member of the G protein-coupled receptor superfamily. This receptor is directly associated with one of its ultimate effectors, the class C L-type calcium channel Ca(V)1.2. This receptor-channel compl', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=154', 'rs1042713Â ', 4),
(1244, 'CVD', 'Stroke', '9734', 'HDAC9', 'GG', 'Histones play a critical role in transcriptional regulation, cell cycle progression, and developmental events. Histone acetylation/deacetylation alters chromosome structure and affects transcription factor access to Diabetic nephropathyA. The protein enco', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9734', 'rs2107595 ', 4),
(1242, 'CVD', 'Stroke', '3552', 'IL1A', 'CC', 'Involved in the inflammatory mechanisms, and were reported to be involved in the pathogenesis of stroke and cardiovascular diseases. Act as proinflammatory cytokines contributing to atherogenesis.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3552', 'rs17561 ', 4),
(1243, 'CVD', 'Stroke', '4815', 'NINJ2', 'GG', '\'NINJ2 encodes ninjurin2, a member of the \'\'ninjurin\'\' or nerve-injury-induced protein family. It plays a role in nerve regeneration and may increase the risk of stroke by altering brain response to ischemic injury.\'', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4815', 'rs11833579', 4),
(1241, 'CVD', 'Coronary Heart Diseases', '7040', 'TGFB1', 'TT', 'This gene encodes a secreted ligand of the TGF-beta (transforming growth factor-beta) superfamily of proteins. Ligands of this family bind various TGF-beta receptors leading to recruitment and activation of SMAD family transcription factors that regulate ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7040', 'rs1800469 ', 4),
(1240, 'CVD', 'Coronary Heart Diseases', '217', 'ALDH2', 'GG', 'This protein belongs to the aldehyde dehydrogenase family of proteins. Aldehyde dehydrogenase is the second enzyme of the major oxidative pathway of alcohol metabolism. Two major liver isoforms of aldehyde dehydrogenase, cytosolic and mitochondrial, can b', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=217', 'rs671', 4),
(1239, 'CVD', 'Coronary Heart Diseases', '25902', 'MTHFD1L', 'GA', 'The protein encoded by this gene is involved in the synthesis of tetrahydrofolate (THF) in the mitochondrion. THF is important in the de novo synthesis of purines and thymidylate and in the regeneration of methionine from homocysteine.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=25902', 'rs6922269', 4),
(1237, 'Vascular Diseases', 'Hypertension', '4846', 'NOS3', 'TT, GG', 'Nitric oxide is a reactive free radical which acts as a biologic mediator in several processes, including neurotransmission and antimicrobial and antitumoral activities. Nitric oxide is synthesized from L-arginine by nitric oxide synthases. Variations in ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4846', 'Â rs1808593', 4),
(1238, 'Vascular Diseases', 'Hypertension', '183', 'AGT', 'CT', 'The protein encoded by this gene, pre-angiotensinogen or angiotensinogen precursor, is expressed in the liver and is cleaved by the enzyme renin in response to lowered blood pressure. The protein is involved in maintaining blood pressure and in the pathog', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=183', 'Â rs699', 4),
(1235, 'Vascular Diseases', 'Hypertension', '185', 'AGTR1', 'AC', 'Angiotensin II is a potent vasopressor hormone and a primary regulator of aldosterone secretion. It is an important effector controlling blood pressure and volume in the cardiovascular system. It acts through at least two types of receptors. This gene enc', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=185', 'Â rs5186', 4),
(1236, 'Vascular Diseases', 'Hypertension', '59272', 'ACE2', 'CC', 'The protein encoded by this gene belongs to the angiotensin-converting enzyme family of dipeptidyl carboxydipeptidases and has considerable homology to human angiotensin 1 converting enzyme. This secreted protein catalyzes the cleavage of angiotensin I in', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=59272', '', 4);
INSERT INTO `panel` (`id`, `phenotype`, `traits`, `gene_id`, `gene`, `genotype`, `description`, `all_publication`, `snp`, `panel_info_id`) VALUES
(1234, 'Vascular Diseases', 'Hypertension', '118', 'ADD1', 'GG', 'Alpha-adducin is a protein that in humans is encoded by the ADD1 gene.  Alpha- and beta-adducin include a protease-resistant N-terminal region and a protease-sensitive, hydrophilic C-terminal region. Adducin binds with high affinity to Ca(2+)/calmodulin a', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=118', 'Â rs4961', 4),
(1233, 'Diabetes', 'Diabetic Neuropathy', '9722', 'NOS1AP', 'TC, CC, AA', 'NOS1AP encodes a cytosolic protein that binds to neuronal nitric oxide synthase (gene-NOS1 or protein-nNOS) via an N-terminal phosphotyrosine binding (PDZ) domain. NOS1AP stabilizes nNOS potentiating its subcellular influence. As a result NOS1AP enhances ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9722', 'rs12143842Â ', 4),
(1232, 'Diabetes', 'Diabetic Neuropathy', '3586', 'IL10', 'AA', 'The protein encoded by this gene is a cytokine produced primarily by monocytes and to a lesser extent by lymphocytes. This cytokine has pleiotropic effects in immunoregulation and inflammation. It down-regulates the expression of Th1 cytokines, MHC class ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3586', 'rs3024491', 4),
(1231, 'Diabetes', 'Diabetic Neuropathy', '7351', 'UCP2', 'GA', 'The uncoupling protein 2 (UCP2) is a member of the mitochondrial inner membrane carrier family and is expressed in many tissues including white adipose tissue, liver, kidney, pancreatic islets, macrophages and retinal endothelial cells and pericytes. UCP2', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7351', 'rs660339 ', 4),
(1230, 'Diabetes', 'Diabetic Neuropathy', '7099', 'TLR4', 'AG, CT', 'TLR4 plays an important role in wound healing and any sort of imbalance in TLR4 mediated signaling may abrogate the proper wound healing cascade. a cytoskeletal protein Flightless I modulate wound inflammation, angiogenesis, and remodeling which act via T', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7099', 'rs10759931 ', 4),
(1229, 'Diabetes', 'Diabetic Nephropathy', '5468', 'PPARG', 'CC', 'This gene encodes a member of the peroxisome proliferator-activated receptor (PPAR) subfamily of nuclear receptors. PPARs form heterodimers with retinoid X receptors (RXRs) and these heterodimers regulate transcription of various genes. Three subtypes of ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5468', 'rs1800571', 4),
(1228, 'Diabetes', 'Diabetic Nephropathy', '9370', 'ADIPOQ', 'GG, TT', 'This gene is expressed in adipose tissue exclusively. It encodes a protein with similarity to collagens X and VIII and complement factor C1q. The encoded protein circulates in the plasma and is involved with metabolic and hormonal processes. Mutations in ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs1501299', 4),
(1227, 'Diabetes', 'Diabetic Nephropathy', '1636', 'ACE', 'CC', 'This gene encodes an enzyme involved in catalyzing the conversion of angiotensin I into a physiologically active peptide angiotensin II. Angiotensin II is a potent vasopressor and aldosterone-stimulating peptide that controls blood pressure and fluid-elec', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1636', 'rs4293', 4),
(1226, 'Diabetes', 'Diabetic Nephropathy', '7422', 'VEGFA', 'CC, GG', 'This gene is a member of the PDGF/VEGF growth factor family. It encodes a heparin-binding protein, which exists as a disulfide-linked homodimer. This growth factor induces proliferation and migration of vascular endothelial cells, and is essential for bot', '', 'rs833061 ', 4),
(1225, 'Diabetes', 'Diabetic Nephropathy', '4846', 'NOS3', 'TT, GG, TT', 'Nitric oxide is a reactive free radical which acts as a biologic mediator in several processes, including neurotransmission and antimicrobial and antitumoral activities. Nitric oxide is synthesized from L-arginine by nitric oxide synthases. Variations in ', '', '', 4),
(1223, 'Diabetes', 'Diabetic Nephropathy', '6513', 'SLC2A1/GLUT1', 'GG, TT', 'This gene encodes a major glucose transporter in the mammalian blood-brain barrier. The encoded protein is found primarily in the cell membrane and on the cell surface, where it can also function as a receptor for human T-cell leukemia virus (HTLV) I and ', '', 'rs841847 ', 4),
(1224, 'Diabetes', 'Diabetic Nephropathy', '185', 'AGTR1', 'AC', 'The protein encoded by this gene, pre-angiotensinogen or angiotensinogen precursor, is expressed in the liver and is cleaved by the enzyme renin in response to lowered blood pressure. The protein is involved in maintaining blood pressure and in the pathog', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=185', 'Â rs5186', 4),
(1222, 'Diabetes', 'Diabetic Nephropathy', '1535', 'CYBA', 'CC', 'Cytochrome b is comprised of a light chain (alpha) and a heavy chain (beta). This gene encodes the light, alpha subunit which has been proposed as a primary component of the microbicidal oxidase system of phagocytes. Mutations in this gene are associated ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1535', 'rs4673', 4),
(1221, 'Diabetes', 'Diabetic Nephropathy', '9844', 'ELMO1', 'GA, GA', 'This gene encodes a member of the engulfment and cell motility protein family. These proteins interact with dedicator of cytokinesis proteins to promote phagocytosis and cell migration. Increased expression of this gene and dedicator of cytokinesis 1 may ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9844', 'rs1345365', 4),
(1220, 'Diabetes', 'Diabetic Nephropathy', '1234', 'CCR5', 'GG', 'Chemokine monocyte chemoattractant protein-1 (MCP-1)/CC-chemokine ligand 2 as a major promoter of inflammation, renal injury, and fibrosis in diabetic nephropathy. Researchers have found that diabetes induces kidney MCP-1 production and that urine MCP-1 l', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1234', 'rs1799987', 4),
(1219, 'Diabetes', 'Diabetic Nephropathy', '3586', 'IL10', 'CC', 'The protein encoded by this gene is a cytokine produced primarily by monocytes and to a lesser extent by lymphocytes. This cytokine has pleiotropic effects in immunoregulation and inflammation. It down-regulates the expression of Th1 cytokines, MHC class ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3586', 'rs3024491', 4),
(1218, 'Diabetes', 'Diabetic Nephropathy', '101804010', 'IL8', 'AT', 'Genetic variations in the genes encoding the inflammatory cytokines might confer susceptibility to Diabetic nephropathy by altering their functions or expressions.', 'https://www.ncbi.nlm.nih.gov/pubmed/25518717/', 'rs4073', 4),
(1215, 'Diabetes', 'Diabetic Nephropathy', '32', 'ACACB', 'CC', 'Catalyzes the ATP-dependent carboxylation of acetyl-CoA to malonyl-CoA. Carries out three functions: biotin carboxyl carrier protein, biotin carboxylase and carboxyltransferase. Involved in inhibition of fatty acid and glucose oxidation and enhancement of', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=32', 'rs2268388', 4),
(1216, 'Diabetes', 'Diabetic Nephropathy', '7040', 'TGFB1', 'TT', 'This gene encodes a secreted ligand of the TGF-beta (transforming growth factor-beta) superfamily of proteins. Ligands of this family bind various TGF-beta receptors leading to recruitment and activation of SMAD family transcription factors that regulate ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7040', 'rs1800471', 4),
(1217, 'Diabetes', 'Diabetic Nephropathy', '6559', 'SLC12A3', 'GG', 'The SLC12A3 gene (solute carrier family 12, member 3) located on 16q13 encodes a thiazide sensitive sodium ions and chlorine ions cotransporter that mediates reabsorption of these ions in the renal distal convoluted tubule and is expressed specifically in', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6559', 'rs11643718', 4),
(1213, 'Diabetes', 'Diabetic Nephropathy', '84735', 'Near CNDP1', 'AC', 'This gene encodes a member of the M20 metalloprotease family. The encoded protein is specifically expressed in the brain, is a homodimeric dipeptidase which was identified as human carnosinase.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=84735', 'rs2346061', 4),
(1214, 'Diabetes', 'Diabetic Nephropathy', '833', 'CARS', 'CC, AA', 'This gene encodes a class 1 aminoacyl-tRNA synthetase, cysteinyl-tRNA synthetase. Each of the twenty aminoacyl-tRNA synthetases catalyzes the aminoacylation of a specific tRNA or tRNA isoaccepting family with the cognate amino acid. This gene is one of se', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=833', 'rs739401', 4),
(1211, 'Diabetes', 'Diabetic Nephropathy', '257019', 'FRMD3', 'CC, GG, AA, AA', 'The protein encoded by this gene is a single pass membrane protein primarily found in ovaries. A similar protein in erythrocytes helps determine the shape of red blood cells, but the function of the encoded protein has not been determined. There is some e', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=257019', 'rs1888747 ', 4),
(1212, 'Diabetes', 'Diabetic Nephropathy', '55748', 'CNDP2', 'TC', 'CNDP2, also known as tissue carnosinase and peptidase A (EC 3.4.13.18), is a nonspecific dipeptidase rather than a selective carnosinase.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=55748', 'rs7577', 4),
(1210, 'Diabetes', 'Diabetic Nephropathy', '23101', 'MCF2L2', 'GT', 'MCF.2 cell line derived transforming sequence-like 2 (MCF2L2) is a guanine-nucleotide exchange factor (GEF) from Rho family. Evidence has demonstrated that GEFs from Rho family are signaling molecules responsible for Rho protein activity. Over-activation ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=23101', 'rs7639705', 4),
(1209, 'Diabetes', 'Diabetic Nephropathy', '6647', 'Near SOD1', 'AA', 'The protein encoded by this gene binds copper and zinc ions and is one of two isozymes responsible for destroying free superoxide radicals in the body. The encoded isozyme is a soluble cytoplasmic protein, acting as a homodimer to convert naturally-occuri', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6647', 'rs2070424', 4),
(1207, 'Diabetes', 'Diabetic Nephropathy', '101804010', 'Near IL8', 'AT', 'Genetic variations in the genes encoding the inflammatory cytokines might confer susceptibility to Diabetic nephropathy by altering their functions or expressions.', 'https://www.ncbi.nlm.nih.gov/pubmed/25518717/', 'rs4073', 4),
(1208, 'Diabetes', 'Diabetic Nephropathy', '6647', 'SOD1', 'GG', 'The protein encoded by this gene binds copper and zinc ions and is one of two isozymes responsible for destroying free superoxide radicals in the body. The encoded isozyme is a soluble cytoplasmic protein, acting as a homodimer to convert naturally-occuri', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6647', 'rs2070424', 4),
(1206, 'Diabetes', 'Diabetic cataract', '5467', 'PPARD', 'AA', 'This gene encodes a member of the peroxisome proliferator-activated receptor (PPAR) family. The encoded protein is thought to function as an integrator of transcriptional repression and nuclear receptor signaling. PPARs are involved in the development of ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5467', 'rs7770619', 4),
(1205, 'Diabetes', 'Diabetic cataract', '57733', 'GBA3', 'AA, CC', 'The protein encoded by this gene is an enzyme that can hydrolyze several types of glycosides. This gene is a polymorphic pseudogene, with the most common allele being the functional allele that encodes the full-length protein. GBA3 was proposed to partici', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=57733', '', 4),
(1204, 'Diabetes', 'Diabetic cataract', '6196', 'RPS6KA2', 'TT, AA', 'This gene encodes a member of the RSK (ribosomal S6 kinase) family of serine/threonine kinases. This kinase contains two non-identical kinase catalytic domains and phosphorylates various substrates, including members of the mitogen-activated kinase (MAPK)', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6196', '', 4),
(1203, 'Diabetes', 'Diabetic cataract', '4739', 'NEDD9', 'GG', 'The protein encoded by this gene is a member of the CRK-associated substrates family. Members of this family are adhesion docking molecules that mediate protein-protein interactions for signal transduction pathways. This protein is a focal adhesion protei', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4739', 'rs10811661', 4),
(1202, 'Diabetes', 'Foot Ulcers', '7422', 'VEGFA', 'AA, CC', 'This gene is a member of the PDGF/VEGFA growth factor family. It encodes a heparin-binding protein, which exists as a disulfide-linked homodimer. This growth factor induces proliferation and migration of vascular endothelial cells, and is essential for bo', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7422', 'rs3025036', 4),
(1201, 'Diabetes', 'Foot Ulcers', '4982', 'TNFRSF11B', 'GC', 'The protein encoded by this gene is a member of the TNF-receptor superfamily. This protein is an osteoblast-secreted decoy receptor that functions as a negative regulator of bone resorption. This protein specifically binds to its ligand, osteoprotegerin l', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4982', 'rs3134069 ', 4),
(1200, 'Diabetes', 'Foot Ulcers', '7099', 'TLR4', 'TC, CC, AG, CT', 'TLR4 plays an important role in wound healing and any sort of imbalance in TLR4 mediated signaling may abrogate the proper wound healing cascade. a cytoskeletal protein Flightless I modulate wound inflammation, angiogenesis, and remodeling which act via T', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7099', 'rs10759931 ', 4),
(1199, 'Diabetes', 'Foot Ulcers', '7099', 'Near TLR4', 'AG', 'TLR4 plays an important role in wound healing and any sort of imbalance in TLR4 mediated signaling may abrogate the proper wound healing cascade. A cytoskeletal protein flightless I modulate wound inflammation, angiogenesis, and remodeling which act via T', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7099', 'rs10759931 ', 4),
(1197, 'Diabetes', 'Diabetic Retinopathy', '6934', 'TCF7L2', 'CC, GG', 'This gene encodes a high mobility group (HMG) box-containing transcription factor that plays a key role in the Wnt signaling pathway. The protein has been implicated in blood glucose homeostasis. Genetic variants of this gene are associated with increased', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6934', 'rs7903146', 4),
(1198, 'Diabetes', 'Foot Ulcers', '7124', 'Near TNF', 'GG', '', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7124', 'rs1800629', 4),
(1196, 'Diabetes', 'Diabetic Retinopathy', '5468', 'PPARG', 'CC', 'This gene encodes a member of the peroxisome proliferator-activated receptor (PPAR) subfamily of nuclear receptors. PPARs form heterodimers with retinoid X receptors (RXRs) and these heterodimers regulate transcription of various genes. Three subtypes of ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&ncbi_mmode=std&from_uid=5468', 'rs1801282', 4),
(1194, 'Diabetes', 'Diabetic Retinopathy', '1636', 'ACE', 'GG', 'The rennin-angiotensin system (RAS) has been implicated in the development of DR, and inhibition the activity of RAS has shown to retard the DR. ACE is a dipeptidyl carboxypeptidase I (EC.3.4.15.1) that activates angiotensin I through cleavage of the carb', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1636', 'rs4293', 4),
(1195, 'Diabetes', 'Diabetic Retinopathy', '9370', 'ADIPOQ', 'TT', 'This gene is expressed in adipose tissue exclusively. It encodes a protein with similarity to collagens X and VIII and complement factor C1q. The encoded protein circulates in the plasma and is involved with metabolic and hormonal processes. Mutations in ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs1501299', 4),
(1192, 'Diabetes', 'Diabetic Retinopathy', '59272', 'ACE2', 'CC, GG', 'The protein encoded by this gene belongs to the angiotensin-converting enzyme family of dipeptidyl carboxydipeptidases and has considerable homology to human angiotensin 1 converting enzyme. This secreted protein catalyzes the cleavage of angiotensin I in', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=59272', ' rs879922 ', 4),
(1193, 'Diabetes', 'Diabetic Retinopathy', '7422', 'VEGFA', 'AA, AA, CC, TT, AA, TT, AA', 'This gene is a member of the PDGF/VEGFA growth factor family. It encodes a heparin-binding protein, which exists as a disulfide-linked homodimer. This growth factor induces proliferation and migration of vascular endothelial cells, and is essential for bo', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7422', 'rs833061 ', 4),
(1191, 'Diabetes', 'Diabetic Retinopathy', '2056', 'EPO', 'CC', 'This gene encodes a secreted, glycosylated cytokine composed of four alpha helical bundles. The encoded protein is mainly synthesized in the kidney, secreted into the blood plasma, and binds to the erythropoietin receptor to promote red blood cell product', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2056', 'rs1617640', 4),
(1190, 'Diabetes', 'Diabetic Retinopathy', '3383', 'CD54 (ICAM1)', 'AA', 'Intercellular adhesion molecule-1 (ICAM1) is a biomarker for endothelial cell dysfunction and inflammation that mediates leucocyte influx and persistent retinal leukostasis, retinal vascular leakage, capillary non-perfusion and endothelial cell injury and', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3383', 'rs5498', 4),
(1188, 'Diabetes', 'Diabetic Retinopathy', '850494', 'ALR2', 'CT', 'AR, the first enzyme of the polyol pathway, probably plays an important role in the pathogenesis of the long-term complications of diabetes by means of alterations that result from sorbitol increase and myo-inositol reduction. AR is responsible for the co', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=850494', 'rs759853 ', 4),
(1189, 'Diabetes', 'Diabetic Retinopathy', '7351', 'UCP2', 'GA', 'The uncoupling protein 2 (UCP2) is a member of the mitochondrial inner membrane carrier family and is expressed in many tissues including white adipose tissue, liver, kidney, pancreatic islets, macrophages and retinal endothelial cells and pericytes. UCP2', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7351', 'rs660339 ', 4),
(1186, 'Diabetes', 'Diabetic Retinopathy', '3075', 'CFH', 'GG', '\'The CFH gene provides instructions for making a protein called complement factor H. This protein helps regulate a part of the body\'\'s immune response known as the complement system. The complement system is a group of proteins that work together to destr', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&ncbi_mmode=std&from_uid=3075', 'rs800292', 4),
(1187, 'Diabetes', 'Diabetic Retinopathy', '177', 'RAGE', 'GA', 'RAGE gene polymorphisms are attractive candidates to influence DR because of pathophysiological data correlating retinopathy and advanced glycation end products (AGEs). AGEs result from the non-enzymatic glycation of proteins and lipids. They are found at', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=177', 'rs1800624', 4),
(1185, 'Diabetes', 'Diabetic Retinopathy', '629', 'CFB', 'GG', 'This gene encodes complement factor B, a component of the alternative pathway of complement activation. Factor B circulates in the blood as a single chain polypeptide. Upon activation of the alternative pathway, it is cleaved by complement factor D yieldi', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=629', 'rs1048709', 4),
(1184, 'Diabetes', 'Diabetic Retinopathy', '7040', 'TGFB1', 'CC', 'This gene encodes a secreted ligand of the TGF-beta (transforming growth factor-beta) superfamily of proteins. Ligands of this family bind various TGF-beta receptors leading to recruitment and activation of SMAD family transcription factors that regulate ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7040', 'rs1800469 ', 4),
(1183, 'Diabetes', 'Diabetic Retinopathy', '6347', 'Near CCL2', 'AA', 'Hyperglycemia accelerates MCP1 production in vascular endothelial cells and retinal pigmented epithelial cells. Moreover, the levels of MCP1 in aqueous and vitreous conditions were significantly increased in patients with diabetic retinopathy. production ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6347', 'Â rs1024611', 4),
(1182, 'Diabetes', 'Diabetic Retinopathy', '2056', 'Near EPO', 'CC', 'This gene encodes a secreted, glycosylated cytokine composed of four alpha helical bundles. The encoded protein is mainly synthesized in the kidney, secreted into the blood plasma, and binds to the erythropoietin receptor to promote red blood cell product', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2056', 'rs1617640', 4),
(1181, 'Diabetes', 'Diabetic Retinopathy', '1124', 'CHN2', 'GG', 'This gene encodes a guanosine triphosphate (GTP)-metabolizing protein that contains a phorbol-ester/diacylglycerol (DAG)-type zinc finger, a Rho-GAP domain, and a SH2 domain. The encoded protein translocates from the cytosol to the Golgi apparatus membran', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1124', ' rs39059 ', 4),
(1180, 'Diabetes', 'Diabetic Retinopathy', '7350', 'Near UCP1', 'AG', 'UCP1 plays a recognized role in protection against oxidative stress, which is one of the major contributors to accelerated loss of retinal capillary cell in diabetes', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7350', 'rs10011540 ', 4),
(1179, 'Diabetes', 'Diabetic Retinopathy', '6258', 'RXRG', 'GG', 'The retinoid-X receptor (RXR) is one of the members of the nuclear hormone receptor superfamily. It forms heterodimers with many nuclear receptors, such as the peroxisome proliferative-activated receptor (PPAR), and mediates the biological effects of seve', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6258', 'rs3818569', 4),
(1178, 'Diabetes', 'Type II Diabetes', '79068', 'FTO', 'AA, TT', 'This gene is a nuclear protein of the AlkB related non-haem iron and 2-oxoglutarate-dependent oxygenase superfamily but the exact physiological function of this gene is not known. Other non-heme iron enzymes function to reverse alkylated Diabetic nephropa', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs9939609', 4),
(1177, 'Diabetes', 'Type II Diabetes', '6934,', 'TCF7L2', 'AA, CC, GG', 'This gene encodes a high mobility group (HMG) box-containing transcription factor that plays a key role in the Wnt signaling pathway. The protein has been implicated in blood glucose homeostasis. Genetic variants of this gene are associated with increased', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6934', 'rs7903146', 4),
(1176, 'Diabetes', 'Type II Diabetes', '9370', 'ADIPOQ', 'GT', 'This gene is expressed in adipose tissue exclusively. It encodes a protein with similarity to collagens X and VIII and complement factor C1q. The encoded protein circulates in the plasma and is involved with metabolic and hormonal processes. Mutations in ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs1501299', 4),
(1175, 'Diabetes', 'Type II Diabetes', '54901', 'CDKAL1', 'AG', 'CDKAL1 gene encode tRNA decoration enzyme, namely methyl transfer enzyme which is responsible for the 2-methylthio-N6-threonylcarbamoyladenosine synthesis of the 37th base of tRNA Lys(UUU). Studies found the mitochondria adenosine triphosphate (ATP) gener', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=54901', 'rs7754840', 4),
(1174, 'Diabetes', 'Type II Diabetes', '3784', 'KCNQ1', 'AA', 'The KCNQ1 gene encodes the pore-forming A-subunit of the voltage-gated K+ channel (KvLQT1), which plays an important role in controlling the ventricular repolarization process. KCNQ1 (potassium voltage-gated channel, KQT-like subfamily, member 1 gene as a', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3784', 'rs2237892', 4),
(1173, 'Diabetes', 'Type II Diabetes', '3667', 'IRS1', 'GG', 'Insulin receptor substrate 1 is a substrate of insulin receptor tyrosine kinase, which plays a central role in the insulin-stimulated signal transduction pathway, and acts as a docking protein between the insulin receptor and the signalling molecules.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3667', 'rs1801278', 4),
(1172, 'Diabetes', 'Type II Diabetes', '11132', 'CAPN10', 'GG', 'CAPN10 gene encodes the protein calpain-10, which is a member of the cysteine protease family that is involved in proinsulin processing, insulin secretion, and insulin resistance', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=11132', 'rs3792267', 4),
(1168, 'Diabetes', 'Type II Diabetes', '10644', 'IGF2BP2', 'GG, AA', 'Insulin-like growth factor 2 mRNA-binding protein 2 (IGF2BP2) belongs to a family of mRNA-binding proteins involved in RNA localization, stability, and translation. IGF2 plays a pivotal role in regulating fetal growth and organogenesis, including adipogen', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=10644', ' rs4402960', 4),
(1169, 'Diabetes', 'Type II Diabetes', '169026', 'SLC30A8 ', 'TT', 'SLC30A8 encodes the secretory granule-resident and largely endocrine pancreas-restricted zinc transporter ZnT8. This gene encodes a recently identified zinc transporter, ZnT8, whose expression is largely confined to the endocrine pancreas within beta (and', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=169026', 'rs13266634', 4),
(1170, 'Diabetes', 'Type II Diabetes', '6517', 'SLC2A4', 'CC', 'This gene is a member of the solute carrier family 2 (facilitated glucose transporter) family and encodes a protein that functions as an insulin-regulated facilitative glucose transporter. In the absence of insulin, this integral membrane protein is seque', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6517', 'rs5435', 4),
(1171, 'Diabetes', 'Type II Diabetes', '7466', 'WFS1', 'GG', 'WFS1 encodes wolframin, a transmembrane glycoprotein that maintains calcium homeostasis of the endoplasmic reticulum. Mutations in this gene causes Wolfram syndrome, characterized by diabetes insipidus, juvenile-onset non-autoimmune diabetes mellitus, opt', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=7466', 'rs6446482', 4),
(1166, 'Diabetes', 'Cardiovascular Diseases', '9370', 'ADIPOQ', 'GT', 'This gene is expressed in adipose tissue exclusively. It encodes a protein with similarity to collagens X and VIII and complement factor C1q. The encoded protein circulates in the plasma and is involved with metabolic and hormonal processes. Mutations in ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs1501299', 4),
(1167, 'Diabetes', 'Type II Diabetes', '3087', 'Near HHEX', 'CT, AG', 'HHEX belongs to a large family of transcription factors that are distinguished by a 60 amino acid conserved DNA-binding homeodomain. It is expressed in the anterior visceral endoderm during early development and in some adult tissues of endodermal origin,', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3087', 'rs5015480', 4),
(1164, 'Lipid Metabolism', 'Cholesterol Levels', ' 3990,', 'LIPC', 'CT', 'LIPC encodes hepatic triglyceride lipase, which is expressed in liver. LIPC has the dual functions of triglyceride hydrolase and ligand/bridging factor for receptor-mediated lipoprotein uptake.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3990', 'rs493258', 4),
(1165, 'Lipid Metabolism', 'Cholesterol Levels', '326625', 'MMAB', 'CC', 'This gene encodes for a protein that catalyses the final step in the conversion of Vitamin B12 into adenosylcobalamin. Mutation in the MMAB gene could result in diminished adenosycobalamin levels and causes accumulation of methyl-malonic acid. Consequentl', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=326625', 'rs11067233', 4),
(1163, 'Lipid Metabolism', 'Cholesterol Levels', '335', 'APOA1', 'AA', 'This gene encodes apolipoprotein A-I, which is the major protein component of high-density lipoprotein (HDL) in plasma. The encoded preproprotein is proteolytically processed to generate the mature protein, which promotes cholesterol efflux from tissues t', ' https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=335', 'rs670', 4),
(1162, 'Lipid Metabolism', 'Cholesterol Levels', '84722', 'PSRC1', 'GA, CA', 'Chromosome 1p13.3 maps in close proximity to the cadherin EGF LAG seven-pass G-type receptor 2 and the proline/serine-rich coiled-coil protein 1 (PSRC1) genes, which regulate cell adhesion, intracellular trafficking, and proliferation; additionally, it ma', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=84722', 'rs464218', 4),
(1156, 'Lipid Metabolism', 'Cholesterol Levels', '6927', 'Near HNF1A', 'AA', 'Hepatocyte nuclear factor 4Î± (HNF4Î±, NR2A1) is a member of the nuclear receptor superfamily. It is highly expressed in the liver, with lower levels in the kidney, intestine and pancreatic Î² cells. Acute loss of hepatic HNF4Î± results in striking phenot', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=6927', 'rs2464196', 4),
(1157, 'Lipid Metabolism', 'Cholesterol Levels', '3172', 'HNF4A', 'CC', 'Hepatocyte nuclear factor 4Î± (HNF4Î±, NR2A1) is a member of the nuclear receptor superfamily. It is highly expressed in the liver, with lower levels in the kidney, intestine and pancreatic Î² cells. Acute loss of hepatic HNF4Î± results in striking phenot', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3172', 'rs3212172', 4),
(1158, 'Lipid Metabolism', 'Cholesterol Levels', '3949', 'LDLR', 'TT', 'The LDLR gene provides instructions for making a protein called a low-density lipoprotein receptor. This receptor binds to particles called low-density lipoproteins (LDLs), which are the primary carriers of cholesterol in the blood.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3949', 'rs5925', 4),
(1159, 'Lipid Metabolism', 'Cholesterol Levels', '341', 'APOC1', 'AA', 'This gene encodes a member of the apolipoprotein C1 family. This gene is expressed primarily in the liver, and it is activated when monocytes differentiate into macrophages. The encoded protein plays a central role in high density lipoprotein (HDL) and ve', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=341', 'rs4420638', 4),
(1160, 'Lipid Metabolism', 'Cholesterol Levels', '1071', 'CETP', 'GA, CA', 'The protein encoded by this gene is found in plasma, where it is involved in the transfer of cholesteryl ester from high density lipoprotein (HDL) to other lipoproteins. Defects in this gene are a cause of hyperalphalipoproteinemia 1 (HALP1).', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1071', 'rs1800777', 4),
(1161, 'Lipid Metabolism', 'Cholesterol Levels', '4023', 'LPL', 'CC, TT, CG, CC', 'This gene encodes for the protein Lipoprotein Lipase. This enzyme breaks down the Triglycerides present in Lipoproteins into free fatty acids.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4023', 'rs12678919', 4),
(1154, 'Lipid Metabolism', 'Cholesterol Levels', '83892', 'KCTD10', 'CC, CC', 'The protein encoded by this gene binds proliferating cell nuclear antigen (PCNA) and may be involved in DNA synthesis and cell proliferation. In addition, the encoded protein may be a tumor suppressor. Several protein-coding and non-protein coding transcr', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=83892', 'rs56209061', 4),
(1155, 'Lipid Metabolism', 'Cholesterol Levels', '3990', 'Near LIPC', 'GG', 'The LIPC gene provides instructions for making an enzyme called hepatic lipase. This enzyme is produced by liver cells and released into the bloodstream where it helps with the conversion of fat-transporting molecules called very low-density lipoproteins ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3990', 'rs493258', 4),
(1152, 'Lipid Metabolism', 'Cholesterol Levels', '9388', 'LIPG', 'CC', 'EL is mainly synthesized by endothelial cells. It is also expressed in the liver, lung, macrophage, testis, ovary, and placenta. EL lipolytic activity showed that the high-density lipoprotein cholesterol (HDL-C) is the preferred substrate for EL.', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9388', 'rs2000813', 4),
(1153, 'Lipid Metabolism', 'Cholesterol Levels', '1952', 'CELSR2', 'CT', 'The protein encoded by this gene is a member of the flamingo subfamily, part of the cadherin superfamily. The flamingo subfamily consists of nonclassic-type cadherins; a subpopulation that does not interact with catenins. The flamingo cadherins are locate', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=1952', 'rs599839', 4),
(1148, 'Lipid Metabolism', 'Triglyceride Levels', '341', 'APOC1', 'AA', 'This gene encodes a member of the apolipoprotein C1 family. This gene is expressed primarily in the liver, and it is activated when monocytes differentiate into macrophages. The encoded protein plays a central role in high density lipoprotein (HDL) and ve', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=341', 'rs4420638', 4),
(1149, 'Lipid Metabolism', 'Triglyceride Levels', '4023', 'LPL', 'CG', 'LPL is an important rate-limiting enzyme for the hydrolysis of circulating Triglyceride, found in chylomicrons and Very Low Density Lipoprotein, into non-esterified fatty acids and 2-monoacylglycerol for tissue utilization and High density Lipoprotein for', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4023', 'rs12678919', 4),
(1150, 'Lipid Metabolism', 'Triglyceride Levels', '345', 'APOC3', 'CC', 'The apolipoprotein C3 gene (APOC3) is a member of the APOA1/C3/A4/A5 gene cluster and located on chromosome 11q23, an area in strong linkage with lipid metabolism. Apolipoprotein C3 (APOC3) is an essential constituent of triglyceride-rich particles includ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=345', 'rs5128 ', 4),
(1151, 'Lipid Metabolism', 'Triglyceride Levels', '116519', 'APOA5', 'TT, CG, AA', 'Encodes Apolipoprotein A-5, major component of VLDL, Chylomicrons, HDL. APOA5 functions as an activator of lipoprotein lipase ( key enzyme in triglyceride catabolism) and inhibits hepatic VLDL-particle production and assembly (by binding to cellular membr', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9388', 'rs662799', 4),
(1146, 'Lipid Metabolism', 'Triglyceride Levels', '8882', 'ZNF259', 'CG, CT, AA', 'ZNF259 genes, which are known to play a key role in lipid metabolism. Lipoprotein (a) consists of a cholesterol-laden low-density lipoprotein (LDL)â€“like particle bound to a plasminogen-like glycoprotein, apolipoprotein (a). Lipoprotein (a) has been show', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=8882', 'rs2075290', 4),
(1147, 'Lipid Metabolism', 'Triglyceride Levels', '2590', 'GALNT2', 'AG', 'GALNT2 modulates HDL metabolism, at least partly, by inducing O-linked glycosylation and increased function of PLTP (i.e. a Phospholipid Transfer Protein), a known positive modulator of serum HDL-C levels', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2590', 'rs2144300  ', 4),
(1145, 'Lipid Metabolism', 'Triglyceride Levels', '84811', 'BUD13', 'GG', 'The BUD13/ZNF259 genes are located on chromosome 11q23.3 and encode for BUD13 homolog protein and zinc finger protein (ZPR1) respectively. BUD13 is one of the subunits of the RES complex, which was previously identified in yeast as a splicing factor that ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=84811', 'rs7118999 ', 4),
(1139, 'Weight Management', 'Obesity', '4160', 'MC4R', 'TC, GA,GA', 'The protein encoded by this gene is a membrane-bound receptor and member of the melanocortin receptor family. The encoded protein interacts with adrenocorticotropic and MSH hormones and is mediated by G proteins. This is an intronless gene. Defects in thi', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4160', 'rs17782313', 4),
(1140, 'Weight Management', 'Obesity', '79068', 'FTO', 'TT, CT, TT, GG, TT', 'This gene is a nuclear protein of the AlkB related non-haem iron and 2-oxoglutarate-dependent oxygenase superfamily but the exact physiological function of this gene is not known. Other non-heme iron enzymes function to reverse alkylated Diabetic nephropa', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=79068', 'rs8050136', 4),
(1141, 'Lipid Metabolism', 'Triglyceride Levels', '348', 'APOE', 'TT', 'The protein encoded by this gene is a major apoprotein of the chylomicron. It binds to a specific liver and peripheral cell receptor, and is essential for the normal catabolism of triglyceride-rich lipoprotein constituents. This gene maps to chromosome 19', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=348', 'rs7412', 4),
(1142, 'Lipid Metabolism', 'Triglyceride Levels', '2646', 'GCKR', 'CC,CC', 'Glucokinase regulatory protein (GKRP; gene symbol: GCKR) is a rate-limiting factor of glucokinase (GCK), which functions as a key glycolytic enzyme for maintaining glucose homeostasis', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=2646', 'rs780094', 4),
(1143, 'Lipid Metabolism', 'Triglyceride Levels', '10221', 'Near TRIB1', 'AA', 'The tribbles family of genes encode a group of highly conserved pseudokinase proteins, which are thought to act as adaptors in several signalling pathways that are intimately involved in the regulation of a number of key cellular processes, including MAPK', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=10221', 'rs17321515', 4),
(1144, 'Lipid Metabolism', 'Triglyceride Levels', '51085', 'MLXIPL', 'CC', 'This gene encodes a basic helix-loop-helix leucine zipper transcription factor of the Myc/Max/Mad superfamily. This protein forms a heterodimeric complex and binds and activates, in a glucose-dependent manner, carbohydrate response element (ChoRE) motifs ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=51085', 'rs3812316', 4),
(1137, 'Weight Management', 'Obesity', '336', 'APOA2', 'TT', 'This gene encodes apolipoprotein (apo-) A-II, which is the second most abundant protein of the high density lipoprotein particles. The protein is found in plasma as a monomer, homodimer, or heterodimer with apolipoprotein D. Defects in this gene may resul', 'https://pubmed.ncbi.nlm.nih.gov/?from_uid=336&linkname=gene_pubmed', 'rs3813627', 4),
(1138, 'Weight Management', 'Obesity', '5468', 'PPARG', 'CC', 'This gene encodes a member of the peroxisome proliferator-activated receptor (PPAR) subfamily of nuclear receptors. PPARs form heterodimers with retinoid X receptors (RXRs) and these heterodimers regulate transcription of various genes. Three subtypes of ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5468', 'rs1800571', 4),
(1136, 'Weight Management', 'Obesity', '9370', 'ADIPOQ', 'AA, GT', 'This gene is expressed in adipose tissue exclusively. It encodes a protein with similarity to collagens X and VIII and complement factor C1q. The encoded protein circulates in the plasma and is involved with metabolic and hormonal processes. Stimulates AM', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=9370', 'rs1501299', 4),
(1135, 'Weight Management', 'Obesity', '116519', 'APOA5', 'CG, TT', 'The protein encoded by this gene is an apolipoprotein that plays an important role in regulating the plasma triglyceride levels, a major risk factor for coronary artery disease. It is a component of high density lipoprotein and is highly similar to a rat ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=116519', 'rs662799', 4),
(1129, 'Weight Management', 'Obesity', '132789', 'Near GNPDA2', 'AA', 'The protein encoded by this gene is an allosteric enzyme that catalyzes the reversible reaction converting D-glucosamine-6-phosphate into D-fructose-6-phosphate and ammonium. Variations of this gene have been reported to be associated with influencing bod', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=132789', 'rs10938397', 4),
(1130, 'Weight Management', 'Obesity', '129787', 'Near TMEM18', 'CC, GG', 'The TMEM18 gene codes for a poorly characterized transmembrane protein. One study indicated that this protein is located in the nuclear envelope in neural stem cells. TMEM18 may be involved in cell migration as overexpression of the protein increases the ', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=129787', 'rs6548238', 4),
(1131, 'Weight Management', 'Obesity', '4828', 'NMB', 'CC', 'This gene encodes a member of the bombesin-like family of neuropeptides, which negatively regulate eating behavior. The encoded protein may regulate colonic smooth muscle contraction through binding to its cognate receptor, the neuromedin B receptor (NMBR', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4828', 'rs3809508', 4),
(1132, 'Weight Management', 'Obesity', '5443', 'POMC', 'CC', 'This gene encodes a preproprotein that undergoes extensive, tissue-specific, post-translational processing via cleavage by subtilisin-like enzymes known as prohormone convertases. The encoded protein is synthesized mainly in corticotroph cells of the ante', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=5443', 'rs1042571', 4),
(1134, 'Weight Management', 'Obesity', '4852', 'NPY', 'GT', 'This gene encodes a neuropeptide that is widely expressed in the central nervous system and influences many physiological processes, including cortical excitability, stress response, food intake, circadian rhythms, and cardiovascular function. Neuropeptid', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=4852', 'rs17149106', 4),
(1133, 'Weight Management', 'Obesity', '3953', 'LEPR', 'AG', 'The protein encoded by this gene belongs to the gp130 family of cytokine receptors that are known to stimulate gene transcription via activation of cytosolic STAT proteins. This protein is a receptor for leptin (an adipocyte-specific hormone that regulate', 'https://www.ncbi.nlm.nih.gov/pubmed?LinkName=gene_pubmed&from_uid=3953', 'rs1137101', 4);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `panel`
--
ALTER TABLE `panel`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `panel`
--
ALTER TABLE `panel`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1269;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
